const config = {
  printWidth: 100,
  tabWidth: 2,
  useTabs: false,
  semi: true,
  singleQuote: false,
  quoteProps: 'as-needed',
  jsxSingleQuote: false,
  trailingComma: 'es5',
  bracketSpacing: true,
  bracketSameLine: false,
  arrowParens: 'always',
  proseWrap: 'preserve',
  htmlWhitespaceSensitivity: 'css',
  endOfLine: 'lf',
  embeddedLanguageFormatting: 'auto',
  singleAttributePerLine: false,
  importOrderSortSpecifiers: true,
  importOrderSeparation: true,
  importOrder: [
    '@simple-online-healthcare/icons',
    '@simple-online-healthcare/ui',
    '@/types',
    '@/utils',
    '@/hooks',
    '@/components',
    '^[./]',
  ],
  plugins: ['@trivago/prettier-plugin-sort-imports'],
};

export default config;
